name: lakehouse

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: lakehouse-minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER} # read from env
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data # presist
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  minio-init:   # create bucket once then exit
    image: quay.io/minio/mc:latest
    container_name: lakehouse-minio-init
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD} &&
      mc mb --ignore-existing local/${MINIO_BUCKET} &&
      echo 'bucket ${MINIO_BUCKET} ready';
      "

  nessie:
    image: ghcr.io/projectnessie/nessie:latest
    container_name: catalog-nessie
    ports:
      - "19120:19120"   # REST API + UI
    environment:
      nessie.version.store.type: ROCKSDB  # presitent catalog
      # nessie.version.store.persist.rocks-db.path: /nessie/data -> commit will disappeare when docker compose down
      nessie.version.store.persist.rocks.database-path: /deployments/data
      # REST API Iceberg config about S3 store in catalog
      nessie.catalog.default-warehouse: warehouse   # root dir in minio where iceberg store data and metadata
      nessie.catalog.warehouses.warehouse.location: s3://lakehouse/warehouse
      nessie.catalog.service.s3.default-options.region: us-east-1
      nessie.catalog.service.s3.default-options.path-style-access: "true"
      nessie.catalog.service.s3.default-options.endpoint: http://minio:9000/
      nessie.catalog.service.s3.default-options.access-key: urn:nessie-secret:quarkus:nessie.catalog.secrets.access-key
      nessie.catalog.secrets.access-key.name: ${MINIO_ROOT_USER}
      nessie.catalog.secrets.access-key.secret: ${MINIO_ROOT_PASSWORD}
    volumes:
      - nessie_data:/deployments/data # store nessie-data and rockdb
    depends_on:
      minio-init:
        condition: service_completed_successfully
    restart: unless-stopped

  trino:
    image: trinodb/trino:latest
    container_name: lakehouse-trino
    ports:
      - "8080:8080"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./trino/etc/catalog:/etc/trino/catalog:ro # mount entire folder but folder mount will above folder root catalog
    depends_on:
      minio-init:
        condition: service_completed_successfully
      nessie:
        condition: service_started
    restart: unless-stopped

  postgres-app: # source app OLTP
    image: postgres:16
    container_name: lakehouse-postgres-app
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: ${APP_PG_USER}
      POSTGRES_PASSWORD: ${APP_PG_PASSWORD}
      POSTGRES_DB: ${APP_PG_DB}
    volumes:
      - postgres_app_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_PG_USER} -d ${APP_PG_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mongo: # source event logs
    image: mongo:7
    container_name: lakehouse-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  airflow:
    build:
      context: .
      dockerfile:  airflow/Dockerfile
    container_name: lakehouse-airflow
    command: airflow standalone
    ports:
      - "8081:8080" # 8080 is also port of trino
    working_dir: /opt/project
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/project/airflow/dags

      VENV: /opt/pipeline/venv/bin
      # Address of another service in compose network
      APP_PG_HOST: postgres-app
      APP_PG_PORT: "5432"
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
      TRINO_HOST: trino
      TRINO_PORT: "8080"
      MINIO_ENDPOINT: http://minio:9000
      NESSIE_URI: http://nessie:19120/iceberg

      # take in env
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      NESSIE_WAREHOUSE: ${NESSIE_WAREHOUSE}
      APP_PG_DB: ${APP_PG_DB}
      APP_PG_USER: ${APP_PG_USER}
      APP_PG_PASSWORD: ${APP_PG_PASSWORD}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - .:/opt/project            # mount repo -> change DAG dont need rebuild
      - airflow_data:/opt/airflow # SQLite metadata + log
    depends_on:
      minio-init:
        condition: service_completed_successfully
      nessie:
        condition: service_started
      trino:
        condition: service_started
    restart: unless-stopped

volumes:
  minio_data:
  postgres_app_data:
  mongo_data:
  nessie_data:
  airflow_data: